spring:
   profiles:
      active:
      - dev
---
spring:
   profiles: dev   #开发环境
   application: 
      name: microservicecloud-config-wby-dev
---
spring:
   profiles: test   #测试环境
   application: 
      name: microservicecloud-config-wby-test
#切记保存为UTF-8格式